name: Continuous Deployment

on:
    push:
        branches: [main]

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              
            - name: Build the application
              run: ./scripts/buildprod.sh
              
            - name: Upload binary artifact
              uses: actions/upload-artifact@v3
              with:
                name: notely-binary
                path: notely
                retention-days: 1

    Deploy:
        runs-on: ubuntu-latest
        needs: Build
        steps:
            - name: Check out code
              uses: actions/checkout@v4
              
            - name: Download binary artifact
              uses: actions/download-artifact@v3
              with:
                name: notely-binary
                path: .
                
            - name: Make binary executable
              run: chmod +x notely
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              
            - id: 'auth'
              name: 'Authenticate to Google Cloud'
              uses: 'google-github-actions/auth@v1'
              with:
                credentials_json: '${{ secrets.GCP_SA_KEY }}'
                
            - name: 'Set up Cloud SDK'
              uses: 'google-github-actions/setup-gcloud@v1'
              
            - name: Configure Docker for GCP Artifact Registry
              run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
              
            - name: Build and Push to GCP Artifact Registry
              run: |
                # Verify binary exists
                ls -la
                
                # Build Docker image
                docker build -t us-central1-docker.pkg.dev/notely-455610/notely-ar-repo/notely:latest .
                
                # Push to Google Artifact Registry
                docker push us-central1-docker.pkg.dev/notely-455610/notely-ar-repo/notely:latest
                
                echo "============================================="
                echo "CONTINUOUS DEPLOYMENT COMPLETE"
                echo "Container image successfully pushed to Artifact Registry"
                echo "Image: us-central1-docker.pkg.dev/notely-455610/notely-ar-repo/notely:latest"
                echo "============================================="