name: Continuous Deployment

on:
    push:
        branches: [main]

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              
            - name: Build the application
              run: ./scripts/buildprod.sh
              
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              
            - name: Build Docker image
              run: |
                docker build -t notely:latest .
                docker tag notely:latest us-central1-docker.pkg.dev/notely-455610/notely-ar-repo/notely:latest

    Deploy:
        runs-on: ubuntu-latest
        needs: Build
        steps:
            - name: Check out code
              uses: actions/checkout@v4
              
            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v1
              
            - name: Install Docker
              uses: docker/setup-buildx-action@v3
              
            - name: Build and Push to GCP Artifact Registry
              run: |
                # Skip Google Cloud authentication for now
                # Just build and output instructions for manual push
                docker build -t notely:latest .
                
                echo "============================================="
                echo "MANUAL DEPLOYMENT INSTRUCTIONS:"
                echo "1. Install gcloud CLI locally"
                echo "2. Authenticate with: gcloud auth login"
                echo "3. Run: gcloud auth configure-docker us-central1-docker.pkg.dev"
                echo "4. Tag image: docker tag notely:latest us-central1-docker.pkg.dev/notely-455610/notely-ar-repo/notely:latest"
                echo "5. Push image: docker push us-central1-docker.pkg.dev/notely-455610/notely-ar-repo/notely:latest"
                echo "============================================="